"""empty message

Revision ID: bfeb757a2961
Revises: None
Create Date: 2019-01-17 09:35:44.664551

"""

# revision identifiers, used by Alembic.
revision = 'bfeb757a2961'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_ad',
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('ad_text', sa.Text(), nullable=True),
    sa.Column('masculine_word_count', sa.Integer(), nullable=True),
    sa.Column('feminine_word_count', sa.Integer(), nullable=True),
    sa.Column('masculine_coded_words', sa.Text(), nullable=True),
    sa.Column('feminine_coded_words', sa.Text(), nullable=True),
    sa.Column('coding', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('hash')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_ad')
    # ### end Alembic commands ###
